name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.3.0
homepage: https://github.com/Baseflow/flutter_cache_manager/tree/master/flutter_cache_manager

environment:
  sdk: ">=2.12.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.2
  file: ">=6.0.0 <8.0.0"
  flutter:
    sdk: flutter
  http: ^1.0.0
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ">=0.26.0 <0.28.0"
  sqflite: ^2.2.8+4
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  flutter_lints: ^2.0.1
